### PR TITLE
Find all the things

### PR DESCRIPTION
**Pull request by theanti9**
- Also iterates over common domain word separators to find a lot more buckets.
- Add more output.
- Fix domain resolution error on wordlist postfix entries.

### CODE REVIEW

**Comment by neilwillgettoit** [comment]
nice. I had been doing the separators manually for different use cases.

**Comment by neilwillgettoit** [comment]
speed took a hit... lol

**Comment by theanti9** [comment]
Well it tests domains at the same rate. It just has 3x more to test. 

I can parallelize it if that's preferable. Python would actually do ok with that in this case.

**Comment by neilwillgettoit** [comment]
eh. let's leave it.

**Pull request merged**
